// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `pj_db.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="pj_db", key="string", value="MsDB::Account"

#include <IceUtil/PushDisableWarnings.h>
#include <IceUtil/StringUtil.h>
#include <IceUtil/PopDisableWarnings.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <pj_db.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

pj_db::pj_db(const Freeze::ConnectionPtr& connection, const std::string& dbName ,bool createDb, const Freeze::IceEncodingCompare& compare)
    : Freeze::Map< ::std::string, ::MsDB::Account, ::Freeze::MapKeyCodec< ::std::string>, ::Freeze::MapValueCodec< ::MsDB::Account>, Freeze::IceEncodingCompare >(connection, dbName, keyTypeId(), valueTypeId(), createDb, compare)
{
}

std::string
pj_db::keyTypeId()
{
    return "string";
}

std::string
pj_db::valueTypeId()
{
    return "::MsDB::Account";
}
